/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package warcraft.UI;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import warcraft.logic.Game;
import warcraft.logic.TextManager;
import warcraft.logic.ThreadManager;

/**
 *
 * @author Xelop
 */
public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    JButton _Play, _Load, _Txt;
    MainMenu _Instance;
    
    
    public MainMenu() {
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize(); //two lines of code for it to start centered
        this.setLocation(dim.width/4-this.getSize().width/4, dim.height/4-this.getSize().height/4);
        
        _Instance = this;
        
        initComponents();
        
        _Play = new JButton(new ImageIcon(BoatInterface.class.getResource("/warcraft/Images/boton_play.png")));
        _Play.setSize(176, 68);
        _lbl_Back.add(_Play);
        _Play.setLocation(150,425);
        _Play.setVisible(true);
        
        _Load = new JButton(new ImageIcon(BoatInterface.class.getResource("/warcraft/Images/boton_load.png")));
        _Load.setSize(176, 68);
        _lbl_Back.add(_Load);
        _Load.setLocation(550,425);
        _Load.setVisible(true);
        
        _Txt = new JButton(new ImageIcon(BoatInterface.class.getResource("/warcraft/Images/boton_txt.png")));
        _Txt.setSize(176, 68);
        _lbl_Back.add(_Txt);
        _Txt.setLocation(350,525);
        _Txt.setVisible(true);
        
        _Play.addActionListener(new ActionListener() {
 
            public void actionPerformed(ActionEvent e)
            { /////////////////////////////////////////////////Creo que hay que moverlo
                TextManager textManager = TextManager.getInstance(); //Necesario??
                ThreadManager threadManager = ThreadManager.getInstance();
                Game game = Game.getInstance();
                game.setBoats(threadManager.mainStrategy());
                
                //////////////////////////////////////////////////////
                OceanInterface newOcean = new OceanInterface(game);
                newOcean.setVisible(true);
                _Instance.dispose();
                
            }
        });
        
         _Load.addActionListener(new ActionListener() {
 
            public void actionPerformed(ActionEvent e)
            {
                //Execute when button is pressed
                new PinLoad(_Instance).setVisible(true);
                _Instance.setVisible(false);
            }
        });
          _Txt.addActionListener(new ActionListener() {
 
            public void actionPerformed(ActionEvent e)
            {
                //Execute when button is pressed
                TextManager.getInstance().generateTXTStrategy();
            }
        });
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        _lbl_Back = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        _lbl_Back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/warcraft/Images/menu.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(_lbl_Back)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(_lbl_Back, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel _lbl_Back;
    // End of variables declaration//GEN-END:variables
}
