/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package warcraft.UI;

import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author Xelop
 */
public class Ocean extends javax.swing.JFrame {

    /**
     * Creates new form Ocean
     */
    public Ocean() {
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize(); //two lines of code for it to start centered
        this.setLocation(dim.width/4-this.getSize().width/4, dim.height/4-this.getSize().height/4); 
        
        initComponents();
        //new BoatInterface(jLabel1, this);
    }
    

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        _pnl_Main = new javax.swing.JLayeredPane();
        _pnl_Boats = new javax.swing.JPanel();
        _lbl_BoatTest = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        _pnl_Background = new javax.swing.JPanel();
        _lbl_Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        _pnl_Boats.setOpaque(false);

        _lbl_BoatTest.setIcon(new javax.swing.ImageIcon(getClass().getResource("/warcraft/Images/boat.png"))); // NOI18N

        javax.swing.GroupLayout _pnl_BoatsLayout = new javax.swing.GroupLayout(_pnl_Boats);
        _pnl_Boats.setLayout(_pnl_BoatsLayout);
        _pnl_BoatsLayout.setHorizontalGroup(
            _pnl_BoatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(_pnl_BoatsLayout.createSequentialGroup()
                .addGap(197, 197, 197)
                .addComponent(_lbl_BoatTest)
                .addGap(303, 303, 303)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        _pnl_BoatsLayout.setVerticalGroup(
            _pnl_BoatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(_pnl_BoatsLayout.createSequentialGroup()
                .addGroup(_pnl_BoatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(_pnl_BoatsLayout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(_lbl_BoatTest))
                    .addGroup(_pnl_BoatsLayout.createSequentialGroup()
                        .addGap(211, 211, 211)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        _pnl_Background.setLayout(null);

        _lbl_Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/warcraft/Images/FondoOcean.png"))); // NOI18N
        _pnl_Background.add(_lbl_Background);
        _lbl_Background.setBounds(0, 0, 900, 650);

        javax.swing.GroupLayout _pnl_MainLayout = new javax.swing.GroupLayout(_pnl_Main);
        _pnl_Main.setLayout(_pnl_MainLayout);
        _pnl_MainLayout.setHorizontalGroup(
            _pnl_MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(_pnl_Background, javax.swing.GroupLayout.DEFAULT_SIZE, 866, Short.MAX_VALUE)
            .addGroup(_pnl_MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(_pnl_Boats, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        _pnl_MainLayout.setVerticalGroup(
            _pnl_MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(_pnl_Background, javax.swing.GroupLayout.DEFAULT_SIZE, 591, Short.MAX_VALUE)
            .addGroup(_pnl_MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(_pnl_Boats, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        _pnl_Main.setLayer(_pnl_Boats, javax.swing.JLayeredPane.DEFAULT_LAYER);
        _pnl_Main.setLayer(_pnl_Background, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(_pnl_Main)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(_pnl_Main)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public JPanel getPanelAction(){
        return _pnl_Boats;
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ocean.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ocean.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ocean.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ocean.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ocean().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel _lbl_Background;
    private javax.swing.JLabel _lbl_BoatTest;
    private javax.swing.JPanel _pnl_Background;
    private javax.swing.JPanel _pnl_Boats;
    private javax.swing.JLayeredPane _pnl_Main;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
